In [104]:
import torch
import numpy as np

# 创建张量

In [105]:
# 创建一个没有初始化的矩阵
x = torch.empty(5, 3)

x

tensor([[ 2.1631e+17,  1.6255e-42, -1.0842e-19],
        [ 1.6783e+00, -3.6893e+19,  1.8807e+00],
        [ 2.0000e+00,  1.4300e+00,  3.6893e+19],
        [ 1.5301e+00, -2.0000e+00,  1.9971e+00],
        [ 0.0000e+00,  1.9908e+00,  0.0000e+00]])

In [106]:
# 创建一个有初始化的矩阵
x = torch.rand(5, 3) # 高斯分布

x

tensor([[0.0329, 0.8989, 0.8740],
        [0.8548, 0.8080, 0.0146],
        [0.5087, 0.1550, 0.4376],
        [0.9013, 0.8470, 0.0852],
        [0.3622, 0.5999, 0.1592]])

In [107]:
# 创建一个0矩阵
x = torch.zeros(5, 3, dtype = torch.long)

x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [108]:
# 直接通过数据创建张量
x = torch.tensor([2.5, 3.5])

x

tensor([2.5000, 3.5000])

In [109]:
# 通过已经有的张量，创建一个尺寸相同的新张量
x = x.new_ones(5, 3, dtype = torch.double)

print('x: ', x)

# 得到相同尺寸的张量，并且使用随机初始化对其进行赋值
y = torch.randn_like(x, dtype = torch.float)

print('\ny: ', y)

x:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

y:  tensor([[-1.1410,  0.1398,  1.0816],
        [ 1.5608,  1.5743,  1.2097],
        [-0.9212, -0.6483, -0.9335],
        [ 0.3416, -0.0719,  0.2440],
        [-0.0181,  0.0900, -0.3598]])


In [110]:
# 得到当前张量的一个尺寸
print(x.size())

torch.Size([5, 3])


In [111]:
r, c = x.size()

print(r, c)

5 3


# 加法操作

In [112]:
x = torch.tensor([[1, 0, 0],
                  [4, 5, 0]])

y = torch.tensor([[4, 5, 5],
                  [1, 0, 5]])

# 方法1
print(x + y)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [113]:
# 方法2
print(torch.add(x, y))

tensor([[5, 5, 5],
        [5, 5, 5]])


In [114]:
# 方法3 - 指定运算结果存储位置
result = torch.empty(2, 3)

print(torch.add(x, y, out = result))

tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [115]:
# 方法4 - 原地置换 y = y + x (所有的in-place操作都有一个下划线后缀)
# eg: x.copy_(y)

print('****************')
print(x + y)
print('****************')
y.add_(x)

print(y)
print('****************')

****************
tensor([[5, 5, 5],
        [5, 5, 5]])
****************
tensor([[5, 5, 5],
        [5, 5, 5]])
****************


# Numpy式切片

In [116]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [117]:
print(x[:, : 2])

tensor([[1, 2],
        [4, 5]])


# 改变张量的形状.view，使用时需保证元素的总个数不发生变化

In [118]:
x = torch.randn(4, 4)

x

tensor([[ 1.0493,  1.9288,  0.2107,  0.2728],
        [ 0.0558, -1.3253, -0.7328,  1.5275],
        [ 1.6579,  0.1510, -1.9766,  0.8303],
        [-0.3829,  0.7786,  0.7743, -2.0790]])

In [119]:
y = x.view(16)

y

tensor([ 1.0493,  1.9288,  0.2107,  0.2728,  0.0558, -1.3253, -0.7328,  1.5275,
         1.6579,  0.1510, -1.9766,  0.8303, -0.3829,  0.7786,  0.7743, -2.0790])

In [120]:
z = x.view(-1, 8) # 行上自动匹配，但是要有8列

z

tensor([[ 1.0493,  1.9288,  0.2107,  0.2728,  0.0558, -1.3253, -0.7328,  1.5275],
        [ 1.6579,  0.1510, -1.9766,  0.8303, -0.3829,  0.7786,  0.7743, -2.0790]])

# 只有一个值的张量可以转化为python中的一个正常数字

In [121]:
x = torch.randn(1)

print(x)
print(x.item())

tensor([-0.3596])
-0.35958799719810486


# torch Tensor 和 Numpy array之间的相互转换

In [122]:
# torch的tensor和numpy的array共享底层的内存空间，因此改变其中一个的值，另一个也会被随之改变

a = torch.ones(5)

a

tensor([1., 1., 1., 1., 1.])

In [123]:
b = a.numpy()

b

array([1., 1., 1., 1., 1.], dtype=float32)

In [124]:
a.add_(1) # 就地所有值加1

print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### 反向转换

In [125]:
a = np.ones(5)

b = torch.from_numpy(a)

np.add(a, 1, out = a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [126]:
torch.cuda.is_available()

False