In [69]:
import torch

在整个pytorch框架中，所有的神经网络上本质上都是一个autograd package（自动求导包）

autograd package提供了一个对Tensors上所有的操作进行自动微分的功能

In [70]:
x1 = torch.ones(3, 3)

x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [71]:
x = torch.ones(2, 2, requires_grad = True)

x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [72]:
y = x + 2

y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [73]:
z = y * y * 3

z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [74]:
print(x.grad_fn) # x是自定义的
print(y.grad_fn) # y是被加法衍生出来的
print(z.grad_fn) # z是被乘法衍生出来的

None


In [75]:
out = z.mean()

print(out) # out由求均值而来

tensor(27., grad_fn=<MeanBackward0>)


In [76]:
a = torch.randn(2, 2)

a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)
print(b.requires_grad)

False
True
True


# 反向传播依靠.backward实现

In [77]:
out.backward()

print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [78]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# 通过代码块限制停止自动求导
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [80]:
# 通过.detach()获得一个新的tensor，拥有相同内容但是不需要自动求导
print(x.requires_grad)
y = x.detach()

print(x.requires_grad)
print(y.requires_grad)
print(x.eq(y).all())

True
True
False
tensor(True)
