In [10]:
import torch

# 创建张量

In [11]:
# 创建一个没有初始化的矩阵
x = torch.empty(5, 3)

x

tensor([[2.1631e+17, 1.6255e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [12]:
# 创建一个有初始化的矩阵
x = torch.rand(5, 3) # 高斯分布

x

tensor([[0.3410, 0.1254, 0.3084],
        [0.2729, 0.2749, 0.5687],
        [0.9317, 0.5851, 0.2401],
        [0.6677, 0.3017, 0.0724],
        [0.8105, 0.8764, 0.7224]])

In [13]:
# 创建一个0矩阵
x = torch.zeros(5, 3, dtype = torch.long)

x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [14]:
# 直接通过数据创建张良
x = torch.tensor([2.5, 3.5])

x

tensor([2.5000, 3.5000])

In [15]:
# 通过已经有的张量，创建一个尺寸相同的新张量
x = x.new_ones(5, 3, dtype = torch.double)

print('x: ', x)

# 得到相同尺寸的张良，并且使用随机初始化对其进行赋值
y = torch.randn_like(x, dtype = torch.float)

print('\ny: ', y)

x:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

y:  tensor([[ 0.8574, -1.3460, -0.3316],
        [ 0.2419, -1.0279,  0.0985],
        [ 0.5980,  0.0219,  0.4523],
        [-1.6150,  0.6518, -0.9690],
        [ 1.0488, -0.4439,  0.5455]])


In [16]:
# 得到当前张良的一个尺寸
print(x.size())

torch.Size([5, 3])


In [17]:
r, c = x.size()

print(r, c)

5 3


# 加法操作

In [18]:
x = torch.tensor([[1, 0, 0],
                  [4, 5, 0]])

y = torch.tensor([[4, 5, 5],
                  [1, 0, 5]])

# 方法1
print(x + y)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [19]:
# 方法2
print(torch.add(x, y))

tensor([[5, 5, 5],
        [5, 5, 5]])


In [20]:
# 方法3 - 指定运算结果存储位置
result = torch.empty(2, 3)

print(torch.add(x, y, out = result))

tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [22]:
# 方法4 - 原地置换 y = y + x (所有的in-place操作都有一个下划线后缀)
# eg: x.copy_(y)

print('****************')
print(x + y)
print('****************')
y.add_(x)

print(y)
print('****************')

****************
tensor([[ 6,  5,  5],
        [ 9, 10,  5]])
****************
tensor([[ 6,  5,  5],
        [ 9, 10,  5]])
****************
